### ISSUE TITLE
Project cannot compile sussessfully in VS2019

### ISSUE THREAD

**Issue by Sudouble** [empirical-soft/command-interpreter#3]
It's a nice project of the command line argument parse! I meet one problem while compling the demo.

> fatal error C1083: 无法打开包括文件: “boost/lexical_cast.hpp”: No such file or directory

It seems need some lib about "boost". 
I didn't find the specification about the "boost" lib at the first time, it is hidding in the last line. I recommand **highlight** the wiki about the dependency of other libraries which can make the user know what to install obviously.

**Comment by chrisaycock** [comment]
I can highlight the dependency line to make it clearer. There is no wiki for this project.

And to be clear, this library isn't for command-line *arguments* (argv). It's to make a command-line *interface* (repl).
